services:

  # https://www.debian.org/releases/

  postgres:
    # https://docs.aws.amazon.com/AmazonRDS/latest/AuroraUserGuide/Aurora.VersionPolicy.html#Aurora.VersionPolicy.MajorVersions
    # https://hub.docker.com/_/postgres/
    image: postgres:16.1-bookworm
    ports:
      - "127.0.0.1:5432:5432"
    environment:
      POSTGRES_USER: interview_user
      POSTGRES_PASSWORD: interview_pass
      POSTGRES_DB: interview_db
    volumes:
      - interview-db-volume:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-d", "interview_db", "-U", "interview_user"]
      interval: 10s
      retries: 5
      start_period: 5s
    restart: always

  redis:
    # https://docs.aws.amazon.com/AmazonElastiCache/latest/red-ug/supported-engine-versions.html
    # https://hub.docker.com/_/redis/
    image: redis:7.2.5-bookworm
    ports:
      - "127.0.0.1:6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 30s
      retries: 50
      start_period: 30s
    restart: always

  localstack:
    container_name: localstack
    image: localstack/localstack
    ports:
      - "127.0.0.1:4566:4566"            # LocalStack Gateway
      - "127.0.0.1:4510-4559:4510-4559"  # external services port range
    environment:
      # LocalStack configuration: https://docs.localstack.cloud/references/configuration/
      - DEBUG=${DEBUG:-0}
    volumes:
      - interview-localstack-volume:/var/lib/localstack
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  interview-db-volume:
  interview-localstack-volume:
